#!/usr/bin/perl

use strict;
use File::Basename qw(dirname);
use Cwd  qw(abs_path);
use lib (dirname abs_path $0);
use SGEtools::Accounts;


my %record;
my $jobid = shift;


SGEInit ();
print "Accounting files:\n";
SGEPrintAccountFiles ();
while (%record = SGEReadRecord ()) {
   if ($record{job_number} == $jobid) {
     SGEPrintRecord (%record);
   }
}

